import React from 'react';

const TermsAndCondition = () => {
  return (
    <div className="container terms-condition">
      <h2 className="d-flex justify-content-center tc-heading text-decoration-underline mb-5 mt-2">TERMS AND CONDITIONS OF VEHICLE LISTING SERVICES</h2>
      <p>
        <span className="tc-heading">INFILA</span> invites you to its Digital World offering its unique Vehicle Lease facilitation services on the below mentioned terms and conditions: This document
        is an electronic record in terms of the amended Information Technology Act, 2000 and rules and regulations made thereunder. This electronic record is generated by a computer system and does
        not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011
        that require publishing the Terms for access or usage of Infila’s Service via Infila Portals. This document meets the stipulations and conditions mentioned in Section 65 B (2) of the Indian
        Evidence Act, 1872.
      </p>
      <h3 className=" tc-heading text-decoration-underline">1. Introduction</h3>
      <p>
        The Services (defined hereinafter) of “INFILA” provided vide its website “WWW.INFILA.IN” and through its Mobile App <span className="tc-heading">“INFILA”</span> (Collectively called as
        Portals) are conceptualised, owned, organised, managed and provided by <span className="tc-heading">STREAD INNOVATIONS PRIVATE LIMITED</span>, A Company incorporated under the Companies Act,
        2013 and having its registered office at # Flat No.705, Block-E, Lodha Meridian, 5th Phase, KPHB Colony, Hyderabad, Telangana State, India. Infila is primarily a facilitation service platform,
        a user friendly Web Application and a medium to connect the owners of vehicles who intend to let out their vehicles on lease with the end users who require the vehicles for a brief period on
        leasehold basis for any temporary personal purpose. The owner of the Vehicle is hereinafter referred to as the “LESSOR” and the user who intend to take the vehicle on Lease is referred to as
        the “LESSEE”, for the sake of brevity.
      </p>
      <h3 className=" tc-heading text-decoration-underline">2. INTERPRETATION</h3>
      <p>
        <ol>
          <li>Contract/Agreement means this Terms of Service together with its Privacy Policy, Fee Policy, Lease Agreement, Schedules and Annexures, (If any)</li>
          <li>The descriptive headings of clauses are inserted solely for convenience of reference and are not intended as complete or accurate descriptions of the content of such Clauses;</li>
          <li>
            The use of words in the singular or plural, or with a particular gender, shall not limit the scope or exclude the application of any provision of this Contract to such person or persons
            unless the context otherwise permits;
          </li>
          <li>The terms “hereof”, “herein”, “hereto” and similar words refer to this entire agreement and not any particular clause, or any other subdivision of this Agreement.</li>
          <li>
            The words “include” or “including” shall be deemed to be followed by “Without limitation” or “but not limited to” whether or not they are followed by such phrases or words of like import;
          </li>
          <li>
            References to any “person” include any natural person, corporation, judicial entity, Association, statutory body, partnership, limited liability company, joint venture, trust, estate,
            unincorporated organization or government, state or any political subdivision, instrumentality, agency etc.
          </li>
          <li>
            Reference to “Clause” or any other agreement or document in this Agreement shall be construed as references to the Clauses of this Agreement, or such other agreement or document, as may be
            amended, modified or supplemented from time to time and shall include a reference to any document which amends, modifies or supplements it, or is entered into, made or given pursuant to or
            in accordance with its terms.
          </li>
        </ol>
      </p>
      <h3 className=" tc-heading text-decoration-underline">3. SCOPE OF SERVICE</h3>
      <p>
        Infila offers a Platform for the Lessors, who subscribe to its services, an opportunity to offer their Vehicles on lease through its website “WWW.INFILA.IN” and through its Mobile App{' '}
        <span className="tc-heading">“INFILA”</span>
        (Collectively called as Portals). It also provides the Lessees a quick search of listed vehicles and an option to take on lease for a short term, any vehicle, suitable to their needs and
        preferences. Once the Lessee selects the Vehicle on Infila’s Portal, the same shall be conveyed to the Lessor through an E-mail, Whatsapp, SMS or message through its Portal and based on the
        mutual consensus between the Lessor and Lessee, Infila shall facilitate for electronic execution of a standard Lease Agreement between the Lessor and Lessee comprehensively setting out all the
        terms and conditions of the Lease including but not limited to Lease Charges, mutual rights and obligations of the Parties, conditions of usage of vehicle, Insurance, handling of contingencies
        like theft, accident, traffic violations etc. After execution of the Lease Agreement, the Lessee shall pay an upfront fee for insuring the Vehicle for the duration of the trip and vehicle
        would be handed over to the Lessee by the Lessor at designated location. The Lessee after the usage of the Vehicle as per the agreed terms shall handover the vehicle to the lessor at the
        designated location and shall make the payment of Lease amount as per the agreed Fee Policy to Infila on its Portals through various payment modes. Infila after deduction of its Facilitation
        fee shall remit the balance Lease amount to the Bank Account of Lessor.
      </p>
      <h3 className=" tc-heading text-decoration-underline">4. PRE-REQUISITES FOR REGISTERING AS LESSOR & FOR GETTING VEHICLE LISTED:</h3>
      <p>
        The Lessors i.e. the Vehicle Owners who intend to lease out their vehicles have to register themselves with Infila to get their vehicles listed on the Portals of Infila. The Lessors and the
        vehicle they are offering for lease have to satisfy the criteria and qualify to the standards set out by Infila for getting it listed on their Portal.
        <ul>
          <li>
            The Lessor should have attained the age of majority and shall have a valid identification document issued by the Government i.e. Aadhar Card, Passport, Voter Identity Card, Pan Card etc.
          </li>
          <li>The Lessor shall hold an Active Bank Account in any Nationalised or Private Bank and also PAN Card issued by the Income Tax Department, Government of India.</li>
          <li>The Lessor should be the Registered Owner of the Vehicle which is sought to be listed.</li>
          <li>The Vehicle should have been registered before the Regional Transport Authority of the State, where the Vehicle is sought to be listed.</li>
          <li>The Vehicle shall not be more than 7 years old and shall not have clocked more than 70,000 Kilometers.</li>
          <li>
            The Vehicle shall have an upto date Insurance coverage Policy and the Insurance Policy should be at least of a Third Party comprehensive Insurance as required under the provisions of Motor
            Vehicle Act,1988.
          </li>
          <li>
            Vehicles having any pending insurance claims, Hypothecation amount recovery claims and or involved in any litigations or subject matter of any claims of whatsoever nature are not eligible
            for being listed on the Portals of Infila. Any non-disclosure or suppression of such facts shall be viewed seriously and the vehicle would be immediately delisted without any notice as
            soon as Infila comes to know about the same.
          </li>
          <li>
            The Vehicle shall be neat, well maintained and shall have the basic accessories, including safety device as per safety standards more fully specified and elaborated in the check list of
            standard inventory attached hereto as Annexure-I.
          </li>
          <li> The Vehicle would be equipped with a special fitment device of Infila for the purpose of ensuring safety and tracking of the Vehicle.</li>
          <li>The Vehicle shall not be subject matter of any subsisting lease agreement or listed on any Car rental, sharing or leasing Platform.</li>
          <li>The Vehicle is in smooth and safe working condition and free of any known faults or defects that would affect its safe operation under normal use.</li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">5. REGISTRATION & ACCOUNT CREATION:</h3>
      <p>
        Subject to the fulfilment of the above mentioned criterion, the Lessor for the purpose of listing his vehicle shall open an account on the Portal of Infila by entering basic information such
        as his full name, date of birth, address, Bank account particulars, vehicle details such as make, model and year of manufacture of the vehicle and the lessor shall also upload the documents
        i.e.
        <ul>
          <li>Valid identification document issued by the Government i.e. Aadhar Card, Passport, Voter Identity Card etc.</li>
          <li>Pan Card</li>
          <li>Cancelled Bank Cheque</li>
          <li>Registration Certificate of Vehicle</li>
          <li>Insurance Policy</li>
          <li>Pollution under Check Certificate</li>
          <li>Photographs of the vehicle taken from four sides of the vehicle.</li>
        </ul>
        The lessor can create the Account with a User name and Password of his choice and all the transactions with Infila shall be through the said account only. The Lessor shall be solely
        responsible for maintaining the confidentiality of his User name and Password and any transactions under the said User name shall always deemed to be transactions made by the Lessor himself
        and the Lessor specifically acknowledges that Infila does not have any liability or responsibility for any unauthorised transactions made by anybody misusing the User name and Password of the
        Lessor. The Lessor confirms that all the information and documents uploaded by him on the Portal of Infila are true and genuine and in the event of any information being found to be false and
        or any of the document/s found to be not genuine, Infila shall have absolute discretion to immediately suspend the account and delist the vehicle and initiate appropriate legal proceedings
        against the Lessor. <br /> The Lessor agrees and acknowledges that Infila at its discretion can verify the genuineness of the information and documents uploaded by the Lessor, either by itself
        or through any third party service, which includes physical verification and assessment of the Vehicle condition.
      </p>
      <h3 className=" tc-heading text-decoration-underline">6. LISTING & SCHEDULING OF VEHICLE: </h3>
      <p>
        The Lessor after creation of his Account with his specified user name and password can List the Vehicle on the Portal of Infila making it visible for any user or prospective lessee and offer
        it for lease. The Lessor shall have the option of scheduling the timings as per the availability of his Vehicle and once the vehicle is booked and confirmed, the Lessor shall ensure the
        delivery of the Vehicle to the lessee at the designated location. In the event of non-delivery of the Vehicle and the Lessor opting for cancellation of any booking, cancellation charges as
        defined in the Fee Policy shall be levied on the Lessor.
      </p>
      <h3 className=" tc-heading text-decoration-underline">7. NO GUARANTEE OF BUSINESS: </h3>
      <p>INFILA does not guarantee that the listing of the Vehicle would automatically fetch bookings and generate business for the Lessor.</p>
      <h3 className=" tc-heading text-decoration-underline">8. NO MARKETING:</h3>
      <p>
        INFILA is not obliged and does not market the offerings of the Lessor and shall not be obliged to recommend the Vehicle to the prospective lessees and in no event does Infila undertake to
        generate or guarantee business to the Lessor.
      </p>
      <h3 className=" tc-heading text-decoration-underline">9. NO PARTNERSHIP:</h3>
      <p>
        INFILA offers only facilitation services and the Agreement herein with the Lessor or Lessee, shall under any circumstances be construed or interpreted to be a Partnership, Joint Venture,
        employment, or agency of Infila with the lessor.
      </p>
      <h3 className=" tc-heading text-decoration-underline">10. TRACKING DEVICE: </h3>
      <p>
        {' '}
        The Lessor shall provide access to the personnel of Infila for installing a Tracking or any other device in the Vehicle and the Lessor shall not under any circumstances remove or tamper the
        said tracking device irrespective of the Vehicle being scheduled for listing or being used for the personal use of the Lessor, until and unless the Agreement with Infila is expressly
        terminated. The lessor would be solely responsible for any damage to the said device and is obligated for indemnifying Infila for any damage to the said device or any consequential loss that
        Infila may sustain owing to the same. Infila shall have the absolute discretion to quantify the damages and initiate any proceedings for recovery of the same.
      </p>
      <h3 className=" tc-heading text-decoration-underline">11. PRE-REQUISITES FOR REGISTERING AS LESSEE:</h3>
      <p>
        <ul>
          <li>The Lessee shall possess a valid, subsisting Four wheeler vehicle driving license.</li>
          <li>
            The lessee shall not be suffering from any medical disorder like epilepsy, seizures, etc., or suffering from any physical or mental incapacity, whereby he is advised not to drive any
            vehicle or incapable of effectively driving any vehicle.
          </li>
          <li>The Lessee shall have Valid identification document issued by the Government i.e. Aadhar Card, Passport, Voter Identity Card etc.</li>
          <li>
            The Lessee should be financially stable having a monthly minimum income of not less than Rs.30,000/- (Rupees Thirty Thousand only) as fortified by the Bank Account Statement of past 6
            months.
          </li>
          <li>
            The lessee shall not have any Criminal record including but not limited to Sedition, Violent Crimes, Offences involving rash and negligent acts endangering human life, Thefts, Robbery,
            Offences related to NDPS, Explosive Substances and other prohibited substances.
          </li>
          <li>The Lessee should not have been declared as a proclaimed or habitual offender or shown as absconding by any Court or investigative agency and or declared as insolvent by any Court.</li>
          <li>
            The Lessee in the last One year should not have committed any vehicle accidents, major traffic violations including drunken driving and has a history of non-payment of pending challans or
            fines.
          </li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">12. REGISTRATION OF LESSEE:</h3>
      <p>
        Subject to the fulfilment of the above mentioned criterion, the Lessee for the purpose of obtaining on hire any listed vehicle on Infila Portal shall open an account on the Portal of Infila by
        entering basic information such as his full name, date of birth, address, Bank account particulars and the lessee shall also upload the documents i.e.
        <ul>
          <li>Valid identification document issued by the Government i.e. Aadhar Card, Passport, Voter Identity Card etc.</li>
          <li>Driving License</li>
          <li>Present Residence Proof</li>
          <li>Pan Card</li>
          <li>Cancelled Bank Cheque</li>
        </ul>
        The lessee can create the Account with a User name and Password of his choice and all the transactions with Infila shall be through the said account only. The Lessee shall be solely
        responsible for maintaining the confidentiality of his User name and Password and any transactions under the said User name shall always deemed to be transactions made by the Lessee himself
        and the Lessee specifically acknowledges that Infila does not have any liability or responsibility for any unauthorised transactions made by using the User name and Password of the Lessee. The
        Lessee confirms that all the information and documents uploaded by him on the Portal of Infila are true and genuine and in the event of any information being found to be false at any stage and
        or any of the document/s found to be not genuine, Infila shall have absolute discretion to initiate appropriate legal proceedings against the Lessee. <br /> The Lessee agrees and acknowledges
        that Infila at its discretion can verify the genuineness of the information and documents uploaded by the Lessee, either by itself or through any third party service.
      </p>
      <h3 className=" tc-heading text-decoration-underline">13. OPTING OF VEHICLE: </h3>
      <p>
        The Lessee after successful login shall have the option of selecting any listed vehicle on the Portal of Infila, as per his preferences and requirements by clicking on the option/selection
        button available against the said Vehicle. The said selection of the vehicle would be immediately conveyed by Infila to the Lessor/ Owner of the said Vehicle through an E-mail, Whatsapp, SMS
        or message through its Portal.
      </p>
      <h3 className=" tc-heading text-decoration-underline">14. LEASE AGREEMENT:</h3>
      <p>
        Infila upon the selection of the Vehicle by the Lessee and acceptance of the Lessor shall facilitate for electronic execution of a standard Lease Agreement between the Lessor and Lessee
        comprehensively setting out all the terms and conditions of the Lease including but not limited to Lease Charges, mutual rights and obligations of the Parties, conditions of usage of vehicle,
        Insurance, handling of contingencies like theft, accident, traffic violations etc.
      </p>
      <h3 className=" tc-heading text-decoration-underline">15. UPFRONT FEE:</h3>
      <p>
        The Lessee at the time of execution of the Lease Agreement shall pay an upfront fee to Infila, which would be determined by Infila as per its fee Policy and mentioned in the Lease Agreement,
        for insuring the vehicle at the time of the trip and Infila shall facilitate such protection plan from time to time on payment of such upfront fee.
      </p>
      <h3 className=" tc-heading text-decoration-underline">16. DELIVERY OF VEHICLE:</h3>
      <p>
        After the execution of Lease Agreement with Lessor and payment of Up-front fee by the Lessee to Infila, the Lessor shall park the Vehicle at a pre-specified designated location within the city
        limits. The Lessor shall provide Infila the Current Google location Map along with detailed address details and prominent landmarks of the area so as to ensure the Lessee to take delivery of
        the Vehicle without any hassle. <br /> The Lessor shall before the delivery of the vehicle get the same cleaned and keep ready all the necessary Original documents i.e. Registration
        Certificate, Insurance Policy, Pollution under Control Certificate and any other essential document/s as mandated by the relevant authorities under applicable law. <br /> The Lessor shall
        handover the vehicle only to the Lessee along with keys and original documents.
      </p>
      <h3 className=" tc-heading text-decoration-underline">17. PERSONAL DELIVERY OF VEHICLE:</h3>
      <p>
        The Lessee also has an option for seeking personal delivery of the Vehicle at his home or any other place of his choice within the City limits by paying additional service amount to Infila and
        the said service amount shall be charged by Infila as per its fee policy taking into consideration the distance between the location specified by the Lessor and the point of handing over of
        vehicle to the Lessee. The said amount shall be charged in addition to the Lease amount agreed as per the Lease Agreement.
      </p>
      <h3 className=" tc-heading text-decoration-underline">18. USAGE OF VEHICLE:</h3>
      <p>
        The Lessee shall drive the Vehicle in a diligent manner within the area as specified in the Lease Agreement and taking the Vehicle beyond the agreed area shall be viewed seriously and the
        Lessee would be liable to pay penalty as levied by Infila at its discretion. The Lessee can also opt for engaging any other person of his choice for driving the Vehicle after intimating Infila
        and the said driver shall also hold a valid driving licence. Lessee shall be liable to pay additional Charges to Infila for the same. The Lessee shall strictly abide by the following
        conditions and the same also apples to the driver opted by him:
        <ul>
          <li>The Lessee shall drive the vehicle within the speed limits and shall not over speed or use the Vehicle for any racing purpose.</li>
          <li>The Lessee shall not use the vehicle for any illegal or unethical acts.</li>
          <li>The Lessee shall not store or transport any banned or prohibited substances in the said vehicle.</li>
          <li>The Lessee shall strictly follow all the Traffic rules and/ or regulations as imposed in the area of usage.</li>
          <li>The Lessee shall not park the vehicle in No parking or Prohibited area.</li>
          <li> The Lessee shall not indulge in any reckless, rash or negligent act whereby it would endanger any human or animal or cause any damage to any property.</li>
          <li>
            The Lessee or the Driver as the case may be, shall not consume liquor or any intoxification substance or any medicine which may cause dizziness or sleep or in any way impedes the senses or
            judgmental capacity of the lessee or the driver.
          </li>
          <li>The Lessee shall be liable to indemnify the Lessor for any damage caused to the car.</li>
          <li>The Lessee shall not tamper with, replace, remove or modify any accessory, equipment or machinery of the Vehicle under any circumstances.</li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">19. CONTINGENCIES DURING USAGE :</h3>
      <p>
        Any contingencies during the usage like accident, damage, theft, traffic violations and confiscation of or involving the vehicle during the Lease Term shall be handled by the Lessor and Lessee
        in accordance with the provisions of the Lease Agreement including alleged damage or other issues. The Lessor and the Lessee further agrees to honestly represent any claims or allegations of
        damage and to work in good faith with each other to resolve any disagreement in keeping with the terms of the Lease Agreement.
      </p>
      <h3 className=" tc-heading text-decoration-underline">20. INSURANCE COVERAGE :</h3>
      <p>
        <ul>
          <li>The Lessor shall maintain a minimum of thirty party comprehensive Vehicle insurance as mandated by Motor Vehicles Act ,1988 for the vehicles with an insurance company of its choice.</li>
          <li>
            The Lessee shall be responsible for payment of all expenses associated with any risks and ensuing damage to the vehicle including without limitation theft, partial, or total destruction
            etc., and in doing so, the Lessee shall be required to avail trip protection plans /insurance through Infila’s Portals and shall be required to avail so at requisite fee (Damage Protection
            Fee) over and above the Lease amount. Lessee acknowledges and agrees to abide to the terms and conditions pertaining to the trip protection plan/insurance, including without limitation its
            coverage, exclusions and process of invocation.
          </li>
          <li>All claim payments from the insurance company shall be made to Lessor via the portal or to designated workshops.</li>
          <li>Infila shall assist the Lessee in administration of claims with the insurance company.</li>
          <li>
            The Lessor understands and undertakes that he/she shall not act in a manner contrary or prejudicial to Infila or the Lessee and extend his/her full co-operation and participation at the
            time of any such claim being invoked under the trip protection plan/insurance.
          </li>
          <li>
            The Lessor also understands and agrees that in the event that the Lessor refuses, interferes, prevents the administration of the claim in any manner or repossesses the vehicle which is
            undergoing any maintenance /repair due to invocation of insurance, he /she shall forfeit any rights to claim damages from the Lessee /insurance company as the case maybe. Neither Infila
            nor the Lessee will be liable to make good any damages in such situation and shall stand discharged of all liabilities therein.
          </li>
          <li>
            The Lessee shall not do or omit to or be done or permit or suffer any act which might or could prejudicially vitiate or affect any such insurance and shall at all times extend full
            co-operation so that the claims can be effectively administrated and invoked with the insurance company.
          </li>
          <li>
            The Lessor also understands and agrees that for the events including but not limited to the below listed, the vehicle shall not be protected under any trip protection plan/insurance, if:
            <ul>
              <li>The damage occurs when the vehicle was in possession of Lessor and/ or occurs due to deliberate/negligent acts of the Lessor itself.</li>
              <li>
                Any damage arising due to normal wear and tear of the vehicle or depreciation in quality or value of the vehicle as such including but not limited to self-heating, electrical arcing or
                leaking etc.
              </li>
              <li> Any specific exclusions as maybe listed by the insurance company in such a trip protection plan/insurance.</li>
            </ul>
          </li>
          <li>
            In case of total loss of vehicle, the Lessor understands and agrees to bind himself to the depreciation level as prescribed under law or as prescribed by the relevant insurance company in
            the line with market practice.
          </li>
          <li>
            The Lessee also understands and agrees that certain damages/incidents as listed below are not covered under such trip protection plans and the Lessee will be fully and personally be held
            liable for all costs and damages.
          </li>
          <li>
            The following shall not be covered under trip protection plan/insurance:
            <ul>
              <li>Any deliberate act of damaging the vehicle by the Lessee or any of his/her co-driver.</li>
              <li>Any damage to the vehicle due to negligence or rash driving on part of the Lessee.</li>
              <li>The Lessee or the Driver as the case may be, was tested with alcohol in blood or breath or used drugs and or other stimulants prohibited by the law.</li>
              <li>
                The Lessee used the vehicle in a manner that is in contravention of law or the traffic regulations (over speeding, driving in restricted areas or any other illegal usage for
                racing/commercial usage etc.)
              </li>
            </ul>
          </li>
          <li>
            In the event of any damage, theft, or destruction of the Vehicle during the Lessee shall promptly inform Infila and render all documentation and information including but not limited to
            information about the accident, assistance in filing of FIR or other relevant details as may be necessary to invoke a claim with the company providing the trip protection plan/insurance
            with the assistance from Infila.
          </li>
          <li>
            Accordingly, the Lessee shall pay to the Lessor, the amount of loss and / or damage not paid under the trip protection plan/insurance and be liable for the following: In case of Damage:
            The difference, if any, between the actual amount incurred in repairing the damage to the Vehicle and the amounts recovered/to be recovered under the Vehicle Insurance.
          </li>
          <li>
            Notwithstanding any such additional trip protection plan/insurance availed , under no circumstances shall Infila be held liable towards the parties or a third party for any loss or damage
            that may be suffered by the parties or a third party, whether or not the same may be attributed to parties.
          </li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">21. RE-DELIVERY OF THE VEHICLE:</h3>
      <p>
        The Lessee after the agreed usage of the vehicle shall deliver back the possession of the Vehicle to the Lessor at the specified/designated location as mentioned in the Lease Agreement, along
        with all its Original Documents as handed over by the Lessor at the beginning of the Trip. The Lessee shall handover the vehicle in a neat condition to the Lessor. The Lessee further agrees
        that:
        <ul>
          <li>
            If the Lessee does not return the vehicle within the specified period, he will be charged penalty as defined in the Infila Fee policy, till such time as the vehicle is returned to the
            Lessor and the same shall also include the costs, expenses, charges etc., incurred by the Lessor for repossession of the Vehicle.
          </li>
          <li>
            In the event of the actual usage varying from the agreed mileage of the vehicle as specified in the Agreement, the Lessee shall also be liable to pay the difference amount as per the Fee
            policy of Infila.
          </li>
          <li>
            In the event of the Lessee returning the Vehicle at any different location other than the designated location, additional charges need to be paid by the Lessee for transportation of the
            vehicle from such place to the designated location.
          </li>
          <li>
            If any damage is caused to the Vehicle, the Lessee will be charged penalty which shall be commensurate to the costs, expenses, charges to be incurred for the restoration of the vehicle to
            its original condition and also for the approximate loss sustained by the lessor due to time taken for repairs etc., as per the Fee policy.
          </li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">22. FINAL PAY AMOUNT:</h3>
      <p>
        The Lessee shall pay the Lease amount for leasing the Vehicle as agreed in the Lease Agreement as per the Fee policy of Infila. The final pay amount shall be inclusive of the additional
        charges for opting personal delivery, for Opting Driver, Fines for violations of the agreed terms, charges for loss of keys, documents, unpaid tolls, traffic violation penalties, Costs for any
        damages which may include both cost of repair as well as insurance cover as per the standard rates in the fee policy, charges for extension of trip time, late returns or returns at wrong
        location and also the applicable taxes in force. The said final pay amount shall be paid directly to Infila on its Portal. Infila, after receiving the amount from the Lessee shall remit the
        amount to the Account of the Lessor, after deducting the facilitation fee and other charges, which shall be calculated as a certain percentage of the Lease amount as per its Fee Policy. The
        payment of the said amounts to the Lessor shall be on a weekly basis and the amounts for the previous week (ending on Sunday) shall be credited to Lessor’s account on the next Saturday. The
        Payments to be made to the Lessor shall be more fully described in the terms set forth in the fee policy as it varies depending upon the class, condition, Make and model of the Vehicle and
        other factors.
      </p>
      <h3 className=" tc-heading text-decoration-underline">23. PAYMENT MODES:</h3>
      <p>
        <ol>
          <li>
            Infila allows the Lessee to make the payments for the Service by any of the following modes: (a) Cheque (b) Demand Draft (c ) RTGS (Real time gross Settlement) (d) CCSI (Credit Card
            Standing instruction) (e) NACH (National automated Clearing House) (f) UPI (United Payments Interface) (g) Digital wallets.
          </li>
          <li>
            It is hereby clarified that Infila does not encourage/prefer that payments be made in cash. Any cash payments made by the Lessee shall be at the Lessee’s sole risk, without any recourse to
            Infila.
          </li>
          <li>
            Lessees shall not share to any employee of Infila any banking related information like Pin number, Passwords etc. that is considered to be sensitive personal information within the meaning
            of Information Technology Act, 2000 as amended or any other law for the time being in force.
          </li>
          <li>
            Lessees are liable to pay additional fee for failed payments, dishonored cheques and shall also be liable to reimburse Infila for all costs of collection including collection agency fees,
            third party fees, legal fees and other ancillary costs.
          </li>
        </ol>
      </p>
      <h3 className=" tc-heading text-decoration-underline">24. CONSEQUENCES OF FAILED PAYMENT/NON-PAYMENT:</h3>
      <p>
        The Lessee acknowledges that any dishonour of the cheque issued by the Lessee will attract the provisions of Section 138 of the Negotiable Instrument Act as amended up to date and is
        punishable with imprisonment which may extend up to two years or with fine which may extend up to twice the amount of the cheque or with both. The Lessee further acknowledges that he can also
        be prosecuted and punished for cheating, breach of trust and other offences under the various provisions of the Indian Penal Code apart from being sued under the Civil law for recovery of
        amounts along with interest @ 18 % interest from the date of default till the date of realisation of amount apart from being liable to pay the costs of the Suit.
      </p>
      <h3 className=" tc-heading text-decoration-underline">25. TERMINATION</h3>
      <p>
        The Term of this Agreement begins upon registration of the Lessor/Lessee and shall continue to apply and shall remain valid till the time the concerned party continues to use the service of
        Infila through its Portals or is terminated by either the Lessor/Lessee or by Infila. If the Lessor/Lessee intend to terminate this Agreement, they may do so by (i) not accessing the Portals
        of Infila; or (ii) closing their account on the Portals for all of the listings or bookings of vehicles, as applicable, where such option is available to them, as the case may be; or (iii) by
        discontinuing any further use of the Portals. Any such termination shall not cancel their obligation to pay for the Infila Services and/or any other services already obtained from Infila
        and/the Portals or affect any liability that may have arisen under the Governing Policies.
        <br /> Additionally, Infila shall have the sole discretion to suspend or terminate this Agreement and discontinue its Services provided through the Portals or otherwise) by providing 30
        (thirty) days’ prior notice to the Lessor. However , Infila may, at any time, with or without notice, suspend or terminate this Agreement if:
        <ul>
          <li>It is required to do so by law or upon request by any law enforcement or other government agencies.</li>
          <li>The provision of the Services to you by Infila is, in its sole discretion, no longer commercially viable to it.</li>
          <li>
            The Lessee fails to make any of the payments or part thereof or any other payment required to be made to Infila hereunder and/or in respect of the Infila Services or any other service
            provided by Infila when such failure continues for a period of 15 (fifteen)calendar days after the due date of such payment.
          </li>
          <li>
            The Lessor/Lessee fails to perform or observe any other covenant, conditions or agreement to be performed or observed by it, under any of the Governing Polices or in any other document
            furnished to Infila in connection herewith.
          </li>
          <li>
            Termination of the listing or the booking on account of any wrongdoing of either party and/or violation of any terms, conditions and obligations of this Agreement and/or the Governing
            policies.
          </li>
          <li>The vehicle is being used for a Prohibited Use, as determined by Infila in its sole discretion.</li>
          <li>Infila has elected to discontinue, with or without reason, access to the Portals and/or the Infila Services (or any part thereof).</li>
          <li>In the event Infila faces any unexpected technical issues or problems that prevent the Portals, and/or any other services provided by Infila from working.</li>
          <li>Any other similar unforeseen circumstances.</li>
          <li>
            Termination of Lease Agreement by the Lessor/Lessee: <br /> Both the Lessor and the Lessee may terminate the Lease Agreement as per the terms of the Lease Agreement.
          </li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">26. EFFECTS OF TERMINATION:</h3>
      <p>
        In case of termination of this Agreement or completion of a booking, in accordance with the terms hereunder and the Governing Policies:
        <ul>
          <li>The Lessee shall promptly and without delay return the Vehicle to the Lessor, as per the vehicle return/repossession terms mentioned herein.</li>
          <li>
            The Lessee shall pay, the outstanding Lease Rental (together with all late payment/charges thereon) and other unpaid sums/charges/costs payable by the Lessee under the Agreement and
            Governing Policies.
          </li>
          <li>The Lessor shall pay, any outstanding amounts due payable by the Lessor under the Agreement and Governing Policies.</li>
          <li>The Lessor shall upon termination make its vehicle available to Infila for removal of the Tracking Device.</li>
        </ul>
      </p>
      <h3 className=" tc-heading text-decoration-underline">27. WAIVER:</h3>
      <p>
        Unless otherwise expressly stated in this Terms of Service, the failure on the part of Infila to exercise or delay in exercising a right or remedy under this Terms shall not constitute a
        waiver of the right or remedy or a waiver of any other rights or remedies and no single or partial exercise of any right or remedy under this Terms of service shall prevent any further
        exercise of the right or remedy or the exercise of any other right or remedy available to Infila.
      </p>
      <h3 className=" tc-heading text-decoration-underline">28. AMENDMENT:</h3>
      <p>
        Infila shall have the discretion to modify, add and amend the terms of service or any part thereof at any point of time and shall not require issuance of any prior intimation to the Lessors,
        Lessee or any person/s about the same and the said amendments shall be effective from the date of upload of the same on its Portal. It shall be the sole responsibility of the Lessors or
        anybody intending to avail the services of Infila to visit the portal and update themselves of the modifications/changes to the Terms of service.
      </p>
      <h3 className=" tc-heading text-decoration-underline">29. SEVERABILITY:</h3>
      <p>
        In the event of any of the terms and conditions herein being determined to be invalid, ultra vires or unenforceable, then the same shall be confined only to that extent and the same shall not
        effect the other terms and conditions in toto and the remaining terms and conditions and the amended or modified terms thereof shall be valid and enforceable.
      </p>
      <h3 className=" tc-heading text-decoration-underline">30. DISCLAIMER AND LIMITATION OF LIABILITY:</h3>
      <p>
        To the fullest extent permitted by law, Infila disclaims all warranties and guarantees express or implied and will not be liable for any direct, consequential, special, indirect, exemplary or
        punitive damages(including without limitation loss of profits, revenue, interest, goodwill) whether in contract, tort(including negligence) or any other legal theory even if Infila has been
        advised of the possibility of such damages and in no event and under any circumstances shall Infila’s maximum aggregate liability exceed Rs.10,000/-. The lessors and lessees consciously
        acknowledge, realise and accept that in the event of having any dispute or being not satisfied with the services offered through the Portal, then the only remedy available for them shall be
        termination of the use of Portal and Infila has no other obligation, liability or responsibility towards them.
      </p>
      <h3 className=" tc-heading text-decoration-underline">31. ASSIGNMENT:</h3>
      <p>
        The Lessors and Lessee shall not be entitled to assign in whole or in part, this Agreement or any of their respective rights or obligations without the express prior consent of Infila. Infila
        shall have absolute discretion to assign in whole or in part this Agreement, or obligations of Infila and in such an event, the assignees shall perform the assigned obligations as per the
        Agreement.
      </p>
      <h3 className=" tc-heading text-decoration-underline">32. FORCE MAJEURE:</h3>
      <p>
        This Agreement and its performance by Infila or the Lessors shall be subject to force majeure. If performance of any service or obligation under the terms and conditions of the General
        Policies, including this Agreement or other third parties in fulfilment of transaction like Personal Delivery of Vehicle, Payment gateways etc., are prevented, restricted, delayed or
        interfered with by reason of labour disputes, strikes, acts of God, floods, lightning, severe weather, shortage of materials, rationing, utility, or communication failures, earthquakes, war,
        revolution, acts of terrorism, civil commotion, acts of public enemies, blockade, pandemic, epidemic, lockdown, embargo or any law, order, proclamation, regulation, ordinance, demand or
        requirement having legal effect of any government or any judicial authority or representative of any such government, or any other act whatsoever, whether similar or dissimilar to those
        referred to in this clause, which are beyond the reasonable commercial control of Infila or its third parties performing such services as sub-contractor and could not have been prevented by
        reasonable precautions (each, a “FORCE MAJEURE EVENT”), then Infila shall be excused from such performance to the extent of and during the period of such performance to the extent of and
        during the period of such Force Majeure event. For the avoidance of doubt, a Force Majeure Event shall exclude any event that a party could reasonably have prevented by testing, work-around,
        or other exercise of diligence. If the period of non-performance exceeds 60 days from the receipt of written notice of the Force Majeure Event, either Infila or the Lessor may by giving
        written notice terminate the Agreement.
      </p>
      <h3 className=" tc-heading text-decoration-underline">33. ARBITRATION:</h3>
      <p>
        All the disputes or difference arising out of or in connection with, this Agreement shall be referred to an independent arbitrator appointed by Infila and his decision shall be final and
        binding on the Parties herein. The Arbitration shall be in accordance with the provisions of the Arbitration & Conciliation Act, 1996. The venue of Arbitration shall be at Hyderabad.
      </p>
      <h3 className=" tc-heading text-decoration-underline">34. GOVERNING LAWS & JURISDICTION:</h3>
      <p>
        This Agreement shall be governed by and construed in accordance with the laws of India and any disputes arising in relation hereto shall be subject to the exclusive jurisdiction of the courts
        in Ranga Reddy District.
      </p>
      <h3 className=" tc-heading text-decoration-underline">35. NOTICES:</h3>
      <p>
        Infila shall send notices to Lessors and Lessees in writing through e-mail or whatsapp/SMS and may be followed by registered post and dispatched through a reputed courier. Any notice refused
        by the Lessor or Lessee would be deemed to have been legally delivered and Lessor or Lessee would be deemed to have received such Notice. Lessors or Lessee can send Notices to Infila in
        writing on customer support e-mail id or to Company’s registered office address.
      </p>
      <h3 className=" tc-heading text-decoration-underline">36. ENTIRE CONTRACT:</h3>
      <p>
        This Contract, including any invoice, Ancillary Policies, Annexures along with Terms of Service hereto forms a single Contract between the parties hereto and constitute the entire
        understanding between the parties with regard to the subject matter hereto and supersede any other Terms between the parties relating to the subject matter hereof. The interpretation of the
        terms and conditions of the Contract by Infila shall be final and binding on all the parties.
      </p>
      <h3 className=" tc-heading text-decoration-underline">37. ACCEPTANCE & ESTOPPEL:</h3>
      <p>
        By clicking the AGREE/ ACCEPT button given below, the Lessor/Lessee unconditionally accepts that they have consciously with an open mind, read and understood the entire Terms and conditions of
        service and its consequences and have voluntarily out of their free will agreed to enter into this contract accepting the terms and conditions in toto. The Lessor/Lessee acknowledges that they
        are estopped from raising any dispute with the reasoning or maintainability of any of the terms and conditions mentioned hereabove and assure that they would abide by all the above terms and
        conditions.
      </p>
    </div>
  );
};

export default TermsAndCondition;
